# Copyright 2018 Peter Dimov

sudo: false

install:
  - git clone https://github.com/boostorg/assert
  - git clone https://github.com/boostorg/bind

script:
  - git -C assert diff --name-status --exit-code origin/master origin/develop
  - git -C bind diff --name-status --exit-code origin/master origin/develop

notifications:
  email:
    on_success: always
