# Copyright 2018 Peter Dimov

sudo: false

env:
  matrix:
    - BOGUS_JOB=true

matrix:

  exclude:
    - env: BOGUS_JOB=true

  include:
    - env: REPO=assert
    - env: REPO=bind
    - env: REPO=core
    - env: REPO=endian
    - env: REPO=filesystem
    - env: REPO=mp11
    - env: REPO=smart_ptr
    - env: REPO=system
    - env: REPO=throw_exception
    - env: REPO=timer

script:
  - git clone https://github.com/boostorg/$REPO && git -C $REPO diff --name-status --exit-code origin/master origin/develop

notifications:
  email:
    on_success: always
